import type { Member, Payment, AttendanceRecord } from '@/context/MembersContext';

const now = Date.now();
const d = (daysAgo: number) => new Date(now - daysAgo * 86400000).toISOString();
const dateStr = (daysOffset: number) =>
  new Date(now + daysOffset * 86400000).toISOString().split('T')[0];

// Generate attendance dates: last N days attended
function attendedDays(numDays: number, skipDays: number[] = []): string[] {
  const dates: string[] = [];
  for (let i = 0; i < numDays; i++) {
    if (!skipDays.includes(i)) {
      dates.push(dateStr(-i));
    }
  }
  return dates;
}

export const MOCK_MEMBERS: Member[] = [
  {
    id: 'm1',
    client_id: 'demo',
    name: 'Peter Njoroge',
    phone: '+254711000001',
    email: 'peter.njoroge@gmail.com',
    date_of_birth: '1992-06-15',
    gender: 'male',
    emergency_contact_name: 'Mary Njoroge',
    emergency_contact_phone: '+254711000099',
    plan: 'monthly_premium',
    plan_label: 'Monthly Premium',
    start_date: dateStr(-30),
    expiry_date: dateStr(28),
    billing_amount: 4500,
    billing_cycle: 'monthly',
    next_billing_date: dateStr(28),
    assigned_trainer: 'James Kariuki',
    status: 'active',
    notes: 'Prefers morning sessions. Working on muscle gain.',
    streak: 14,
    last_visit_at: d(1),
    total_visits: 26,
    height_cm: 178,
    weight_kg: 74,
    fitness_goal: 'Muscle Gain',
    created_at: d(30),
    updated_at: d(1),
  },
  {
    id: 'm2',
    client_id: 'demo',
    name: 'Grace Wanjiru',
    phone: '+254722000002',
    email: 'grace.w@outlook.com',
    date_of_birth: '1995-11-20',
    gender: 'female',
    emergency_contact_name: null,
    emergency_contact_phone: null,
    plan: 'annual_basic',
    plan_label: 'Annual Basic',
    start_date: dateStr(-120),
    expiry_date: dateStr(245),
    billing_amount: 36000,
    billing_cycle: 'annual',
    next_billing_date: dateStr(245),
    assigned_trainer: 'Fatuma Ali',
    status: 'active',
    notes: null,
    streak: 3,
    last_visit_at: d(2),
    total_visits: 78,
    height_cm: 163,
    weight_kg: 58,
    fitness_goal: 'Weight Loss',
    created_at: d(120),
    updated_at: d(2),
  },
  {
    id: 'm3',
    client_id: 'demo',
    name: 'John Mutua',
    phone: '+254733000003',
    email: 'john.mutua@gmail.com',
    date_of_birth: '1988-03-07',
    gender: 'male',
    emergency_contact_name: 'Lucy Mutua',
    emergency_contact_phone: '+254733000098',
    plan: 'monthly_basic',
    plan_label: 'Monthly Basic',
    start_date: dateStr(-27),
    expiry_date: dateStr(3),        // EXPIRING SOON
    billing_amount: 2500,
    billing_cycle: 'monthly',
    next_billing_date: dateStr(3),
    assigned_trainer: 'David Omondi',
    status: 'active',
    notes: 'Plans to upgrade to Premium next cycle.',
    streak: 7,
    last_visit_at: d(0),
    total_visits: 20,
    height_cm: 182,
    weight_kg: 88,
    fitness_goal: 'General Fitness',
    created_at: d(27),
    updated_at: d(0),
  },
  {
    id: 'm4',
    client_id: 'demo',
    name: 'Sarah Kimani',
    phone: '+254744000004',
    email: 'sarah.kimani@yahoo.com',
    date_of_birth: '1998-09-14',
    gender: 'female',
    emergency_contact_name: null,
    emergency_contact_phone: null,
    plan: 'monthly_premium',
    plan_label: 'Monthly Premium',
    start_date: dateStr(-60),
    expiry_date: dateStr(18),
    billing_amount: 4500,
    billing_cycle: 'monthly',
    next_billing_date: null,
    assigned_trainer: 'Fatuma Ali',
    status: 'frozen',
    notes: 'On maternity leave. Returning June.',
    streak: 0,
    last_visit_at: d(38),
    total_visits: 42,
    height_cm: 160,
    weight_kg: 62,
    fitness_goal: 'Toning',
    created_at: d(60),
    updated_at: d(38),
  },
  {
    id: 'm5',
    client_id: 'demo',
    name: 'Mike Ochieng',
    phone: '+254755000005',
    email: 'm.ochieng@gmail.com',
    date_of_birth: '1990-01-30',
    gender: 'male',
    emergency_contact_name: 'Clara Ochieng',
    emergency_contact_phone: '+254755000097',
    plan: 'annual_premium',
    plan_label: 'Annual Premium',
    start_date: dateStr(-105),
    expiry_date: dateStr(260),
    billing_amount: 72000,
    billing_cycle: 'annual',
    next_billing_date: dateStr(260),
    assigned_trainer: 'James Kariuki',
    status: 'active',
    notes: 'Training for Nairobi Marathon. 6am sessions Mon–Fri.',
    streak: 21,
    last_visit_at: d(0),
    total_visits: 98,
    height_cm: 175,
    weight_kg: 70,
    fitness_goal: 'Endurance',
    created_at: d(105),
    updated_at: d(0),
  },
  {
    id: 'm6',
    client_id: 'demo',
    name: 'Aisha Abdi',
    phone: '+254766000006',
    email: 'aisha.abdi@gmail.com',
    date_of_birth: '1993-07-22',
    gender: 'female',
    emergency_contact_name: null,
    emergency_contact_phone: null,
    plan: 'pay_per_class',
    plan_label: 'Pay Per Class',
    start_date: dateStr(-90),
    expiry_date: dateStr(-45),
    billing_amount: 800,
    billing_cycle: 'one_time',
    next_billing_date: null,
    assigned_trainer: null,
    status: 'inactive',
    notes: 'Dropped off after Ramadan. Try re-engage.',
    streak: 0,
    last_visit_at: d(62),
    total_visits: 11,
    height_cm: 165,
    weight_kg: 55,
    fitness_goal: 'Flexibility',
    created_at: d(90),
    updated_at: d(62),
  },
  {
    id: 'm7',
    client_id: 'demo',
    name: 'Daniel Karanja',
    phone: '+254777000007',
    email: 'd.karanja@gmail.com',
    date_of_birth: '1985-12-03',
    gender: 'male',
    emergency_contact_name: null,
    emergency_contact_phone: null,
    plan: 'monthly_basic',
    plan_label: 'Monthly Basic',
    start_date: dateStr(-58),
    expiry_date: dateStr(-5),       // EXPIRED
    billing_amount: 2500,
    billing_cycle: 'monthly',
    next_billing_date: null,
    assigned_trainer: 'David Omondi',
    status: 'expired',
    notes: 'Reached out twice. No response.',
    streak: 0,
    last_visit_at: d(18),
    total_visits: 35,
    height_cm: 170,
    weight_kg: 82,
    fitness_goal: 'Weight Loss',
    created_at: d(58),
    updated_at: d(18),
  },
  {
    id: 'm8',
    client_id: 'demo',
    name: 'Wanjiku Mwangi',
    phone: '+254788000008',
    email: 'wanjiku.m@gmail.com',
    date_of_birth: '1997-04-08',
    gender: 'female',
    emergency_contact_name: 'Joseph Mwangi',
    emergency_contact_phone: '+254788000096',
    plan: 'monthly_premium',
    plan_label: 'Monthly Premium',
    start_date: dateStr(-25),
    expiry_date: dateStr(5),        // EXPIRING SOON
    billing_amount: 4500,
    billing_cycle: 'monthly',
    next_billing_date: dateStr(-10), // OVERDUE
    assigned_trainer: 'Priya Patel',
    status: 'active',
    notes: 'Very consistent attendee. Interested in personal training.',
    streak: 5,
    last_visit_at: d(1),
    total_visits: 22,
    height_cm: 158,
    weight_kg: 60,
    fitness_goal: 'Toning',
    created_at: d(25),
    updated_at: d(1),
  },
  {
    id: 'm9',
    client_id: 'demo',
    name: 'Tom Omondi',
    phone: '+254799000009',
    email: 'tom.omondi@outlook.com',
    date_of_birth: '1991-08-19',
    gender: 'male',
    emergency_contact_name: null,
    emergency_contact_phone: null,
    plan: 'monthly_basic',
    plan_label: 'Monthly Basic',
    start_date: dateStr(-18),
    expiry_date: dateStr(12),
    billing_amount: 2500,
    billing_cycle: 'monthly',
    next_billing_date: dateStr(-8), // OVERDUE
    assigned_trainer: null,
    status: 'active',
    notes: null,
    streak: 0,
    last_visit_at: d(22),
    total_visits: 5,
    height_cm: 185,
    weight_kg: 91,
    fitness_goal: 'General Fitness',
    created_at: d(18),
    updated_at: d(22),
  },
];

// Payments per member
export const MOCK_PAYMENTS: Record<string, Payment[]> = {
  m1: [
    { id: 'p1a', member_id: 'm1', amount: 4500, method: 'mpesa', status: 'paid', date: dateStr(-30), reference: 'QAJ9X112', note: null },
    { id: 'p1b', member_id: 'm1', amount: 4500, method: 'mpesa', status: 'paid', date: dateStr(-60), reference: 'QAJ8X009', note: null },
    { id: 'p1c', member_id: 'm1', amount: 4500, method: 'mpesa', status: 'paid', date: dateStr(-90), reference: 'QAJ7X001', note: null },
  ],
  m2: [
    { id: 'p2a', member_id: 'm2', amount: 36000, method: 'bank_transfer', status: 'paid', date: dateStr(-120), reference: 'ANNUAL-2025', note: 'Annual payment' },
  ],
  m3: [
    { id: 'p3a', member_id: 'm3', amount: 2500, method: 'cash', status: 'paid', date: dateStr(-27), reference: null, note: null },
    { id: 'p3b', member_id: 'm3', amount: 2500, method: 'cash', status: 'pending', date: dateStr(3), reference: null, note: 'Renewal due' },
  ],
  m5: [
    { id: 'p5a', member_id: 'm5', amount: 72000, method: 'card', status: 'paid', date: dateStr(-105), reference: 'CARD-7834', note: 'Annual Premium' },
  ],
  m8: [
    { id: 'p8a', member_id: 'm8', amount: 4500, method: 'mpesa', status: 'paid', date: dateStr(-25), reference: 'QBM2K441', note: null },
    { id: 'p8b', member_id: 'm8', amount: 4500, method: 'mpesa', status: 'failed', date: dateStr(-10), reference: null, note: 'M-Pesa timeout' },
  ],
  m9: [
    { id: 'p9a', member_id: 'm9', amount: 2500, method: 'cash', status: 'paid', date: dateStr(-18), reference: null, note: null },
    { id: 'p9b', member_id: 'm9', amount: 2500, method: 'mpesa', status: 'pending', date: dateStr(-8), reference: null, note: 'Overdue' },
  ],
};

// Attendance (days visited this month) per member — as YYYY-MM-DD strings
export const MOCK_ATTENDANCE: Record<string, AttendanceRecord[]> = {
  m1: attendedDays(14).map((date, i) => ({
    date,
    time_in: i % 3 === 0 ? '06:15' : '07:00',
    duration_minutes: 60 + (i % 3) * 15,
  })),
  m2: attendedDays(8, [3, 6]).map((date, i) => ({
    date,
    time_in: '08:30',
    duration_minutes: 45,
  })),
  m3: attendedDays(7).map((date, i) => ({
    date,
    time_in: '17:00',
    duration_minutes: 50,
  })),
  m5: attendedDays(21, [7, 14]).map((date, i) => ({
    date,
    time_in: '06:00',
    duration_minutes: 90,
  })),
  m8: attendedDays(5).map((date, i) => ({
    date,
    time_in: '09:00',
    duration_minutes: 55,
  })),
};

export const MOCK_TRAINERS = [
  'James Kariuki',
  'Priya Patel',
  'David Omondi',
  'Fatuma Ali',
];
