import type { AppLead, LeadActivity } from '@/context/LeadsContext';

export const MOCK_LEADS: AppLead[] = [
  {
    id: '1',
    client_id: 'demo',
    name: 'Brian Kamau',
    phone: '+254712345678',
    email: 'brian.kamau@gmail.com',
    source: 'instagram',
    status: 'trial_booked',
    interests: ['membership', 'personal_training'],
    notes: 'Saw our Instagram story. Wants to try 7am sessions.',
    last_contacted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: '2',
    client_id: 'demo',
    name: 'Amina Odhiambo',
    phone: '+254723456789',
    email: 'amina.o@outlook.com',
    source: 'website',
    status: 'new_lead',
    interests: ['group_classes'],
    notes: null,
    last_contacted_at: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: '3',
    client_id: 'demo',
    name: 'Kevin Mwangi',
    phone: '+254734567890',
    email: null,
    source: 'referral',
    status: 'joined_gym',
    interests: ['membership'],
    notes: 'Referred by Brian. Started 3-month package.',
    last_contacted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: '4',
    client_id: 'demo',
    name: 'Fatuma Hassan',
    phone: '+254745678901',
    email: 'fatuma.h@gmail.com',
    source: 'google_ads',
    status: 'contacted',
    interests: ['personal_training', 'group_classes'],
    notes: 'Interested in evening slots. Following up Thursday.',
    last_contacted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: '5',
    client_id: 'demo',
    name: 'James Otieno',
    phone: '+254756789012',
    email: 'j.otieno@yahoo.com',
    source: 'walk_in',
    status: 'trial_completed',
    interests: ['membership', 'personal_training'],
    notes: 'Completed trial on Monday. Send closing offer.',
    last_contacted_at: new Date(Date.now() - 0.5 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 0.5 * 86400000).toISOString(),
  },
  {
    id: '6',
    client_id: 'demo',
    name: 'Lydia Wanjiku',
    phone: '+254767890123',
    email: 'lydia.w@gmail.com',
    source: 'instagram',
    status: 'lost_lead',
    interests: ['group_classes'],
    notes: 'Went with another gym closer to her office.',
    last_contacted_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: '7',
    client_id: 'demo',
    name: 'David Njoroge',
    phone: '+254778901234',
    email: 'dnjoroge@gmail.com',
    source: 'website',
    status: 'new_lead',
    interests: ['membership'],
    notes: null,
    last_contacted_at: null,
    created_at: new Date(Date.now() - 0.2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 0.2 * 86400000).toISOString(),
  },
  {
    id: '8',
    client_id: 'demo',
    name: 'Priya Sharma',
    phone: '+254789012345',
    email: 'priya.s@gmail.com',
    source: 'referral',
    status: 'contacted',
    interests: ['personal_training'],
    notes: 'Looking for a female trainer. Prefers mornings.',
    last_contacted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
];

export const MOCK_ACTIVITIES: Record<string, LeadActivity[]> = {
  '1': [
    { id: 'a1', lead_id: '1', type: 'trial_booked', description: 'Trial session booked for Friday 7am', created_at: new Date(Date.now() - 1 * 86400000).toISOString() },
    { id: 'a2', lead_id: '1', type: 'stage_changed', description: 'Stage changed to Trial Booked', created_at: new Date(Date.now() - 1 * 86400000).toISOString() },
    { id: 'a3', lead_id: '1', type: 'call_made', description: 'Called Brian — confirmed interest', created_at: new Date(Date.now() - 3 * 86400000).toISOString() },
    { id: 'a4', lead_id: '1', type: 'stage_changed', description: 'Stage changed to Contacted', created_at: new Date(Date.now() - 3 * 86400000).toISOString() },
    { id: 'a5', lead_id: '1', type: 'lead_created', description: 'Lead added from Instagram', created_at: new Date(Date.now() - 5 * 86400000).toISOString() },
  ],
  '3': [
    { id: 'b1', lead_id: '3', type: 'stage_changed', description: 'Stage changed to Joined Gym', created_at: new Date(Date.now() - 3 * 86400000).toISOString() },
    { id: 'b2', lead_id: '3', type: 'trial_booked', description: 'Completed trial session', created_at: new Date(Date.now() - 5 * 86400000).toISOString() },
    { id: 'b3', lead_id: '3', type: 'lead_created', description: 'Lead added via referral (Brian Kamau)', created_at: new Date(Date.now() - 14 * 86400000).toISOString() },
  ],
  '5': [
    { id: 'c1', lead_id: '5', type: 'stage_changed', description: 'Stage changed to Trial Completed', created_at: new Date(Date.now() - 0.5 * 86400000).toISOString() },
    { id: 'c2', lead_id: '5', type: 'trial_booked', description: 'Trial session completed on Monday', created_at: new Date(Date.now() - 3 * 86400000).toISOString() },
    { id: 'c3', lead_id: '5', type: 'note_added', description: 'Note: Walked in asking about memberships', created_at: new Date(Date.now() - 8 * 86400000).toISOString() },
    { id: 'c4', lead_id: '5', type: 'lead_created', description: 'Walk-in lead added', created_at: new Date(Date.now() - 8 * 86400000).toISOString() },
  ],
};
