import type { GymClass, ClassAttendee, WaitlistEntry, ClassTrainer } from '@/context/ClassesContext';

const now = new Date();
const today = now.toISOString().split('T')[0];
const dateStr = (offset: number) =>
  new Date(Date.now() + offset * 86400000).toISOString().split('T')[0];

// Current hour/min for generating in-progress class
const nowH = now.getHours();
const nowM = now.getMinutes();
function padTime(h: number, m = 0) {
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
}

export const MOCK_TRAINERS: ClassTrainer[] = [
  { id: 't1', name: 'James Kariuki',  role: 'Head Trainer',        specialization: 'Strength & HIIT',    avatar_initials: 'JK', color: '#4C9FFF' },
  { id: 't2', name: 'Priya Patel',    role: 'Wellness Coach',      specialization: 'Yoga & Pilates',     avatar_initials: 'PP', color: '#A855F7' },
  { id: 't3', name: 'David Omondi',   role: 'Cardio Specialist',   specialization: 'Cardio & Spinning',  avatar_initials: 'DO', color: '#F97316' },
  { id: 't4', name: 'Fatuma Ali',     role: 'Combat Coach',        specialization: 'Boxing & General',  avatar_initials: 'FA', color: '#33D169' },
];

export const MOCK_CLASSES: GymClass[] = [
  // ── TODAY ──────────────────────────────────────────────────────────────────
  {
    id: 'cl1',
    name: 'Morning HIIT',
    category: 'hiit',
    description: 'High-intensity interval training to kick-start your metabolism. Suitable for intermediate to advanced members.',
    type: 'recurring',
    date: today,
    start_time: '06:00',
    end_time: '07:00',
    location: 'Main Floor',
    max_capacity: 25,
    booked_count: 20,
    trainer_id: 't1',
    status: 'active',
    allow_waitlist: true,
    max_waitlist: 5,
    repeat: 'weekly',
    end_date: dateStr(60),
    created_at: dateStr(-14),
  },
  {
    id: 'cl2',
    name: 'Yoga Flow',
    category: 'yoga',
    description: 'A relaxing vinyasa flow to improve flexibility and mindfulness. All levels welcome.',
    type: 'recurring',
    date: today,
    start_time: '07:30',
    end_time: '08:30',
    location: 'Studio A',
    max_capacity: 15,
    booked_count: 12,
    trainer_id: 't2',
    status: 'active',
    allow_waitlist: false,
    max_waitlist: 0,
    repeat: 'weekly',
    end_date: null,
    created_at: dateStr(-30),
  },
  {
    id: 'cl3',
    name: 'Spinning Blast',
    category: 'spinning',
    description: 'Indoor cycling at high intensity. Bring a towel — it gets intense!',
    type: 'recurring',
    date: today,
    start_time: padTime(nowH - 1 < 0 ? 9 : nowH - 1, nowM),
    end_time:   padTime(nowH + 0, nowM),           // in progress right now
    location: 'Spin Studio',
    max_capacity: 20,
    booked_count: 20,
    trainer_id: 't3',
    status: 'active',
    allow_waitlist: true,
    max_waitlist: 3,
    repeat: 'weekly',
    end_date: null,
    created_at: dateStr(-10),
  },
  {
    id: 'cl4',
    name: 'Boxing Fundamentals',
    category: 'boxing',
    description: 'Learn basic boxing techniques, footwork, and combinations. Great for fitness and self-defence.',
    type: 'one_time',
    date: today,
    start_time: '12:00',
    end_time: '13:00',
    location: 'Main Floor',
    max_capacity: 12,
    booked_count: 8,
    trainer_id: 't4',
    status: 'active',
    allow_waitlist: false,
    max_waitlist: 0,
    repeat: undefined,
    end_date: null,
    created_at: dateStr(-5),
  },
  {
    id: 'cl5',
    name: 'Strength & Conditioning',
    category: 'strength',
    description: 'Progressive overload strength program. Barbell, dumbbell, and bodyweight movements.',
    type: 'recurring',
    date: today,
    start_time: '17:00',
    end_time: '18:00',
    location: 'Weight Room',
    max_capacity: 20,
    booked_count: 15,
    trainer_id: 't1',
    status: 'active',
    allow_waitlist: true,
    max_waitlist: 5,
    repeat: 'weekly',
    end_date: null,
    created_at: dateStr(-20),
  },
  {
    id: 'cl6',
    name: 'Pilates Core',
    category: 'pilates',
    description: 'Core-focused Pilates using mat and resistance bands. Perfect for posture and stability.',
    type: 'recurring',
    date: today,
    start_time: '18:30',
    end_time: '19:30',
    location: 'Studio A',
    max_capacity: 12,
    booked_count: 10,
    trainer_id: 't2',
    status: 'active',
    allow_waitlist: false,
    max_waitlist: 0,
    repeat: 'weekly',
    end_date: null,
    created_at: dateStr(-8),
  },
  {
    id: 'cl7',
    name: 'Evening Cardio',
    category: 'cardio',
    description: 'Mixed cardio circuits: rowing, jump rope, battle ropes. High energy session.',
    type: 'recurring',
    date: today,
    start_time: '20:00',
    end_time: '21:00',
    location: 'Main Floor',
    max_capacity: 18,
    booked_count: 6,
    trainer_id: 't3',
    status: 'active',
    allow_waitlist: false,
    max_waitlist: 0,
    repeat: 'weekly',
    end_date: null,
    created_at: dateStr(-3),
  },

  // ── TOMORROW ───────────────────────────────────────────────────────────────
  {
    id: 'cl8',
    name: 'Morning HIIT',
    category: 'hiit',
    description: 'High-intensity interval training to kick-start your metabolism.',
    type: 'recurring',
    date: dateStr(1),
    start_time: '06:00',
    end_time: '07:00',
    location: 'Main Floor',
    max_capacity: 25,
    booked_count: 9,
    trainer_id: 't1',
    status: 'active',
    allow_waitlist: true,
    max_waitlist: 5,
    repeat: 'weekly',
    end_date: dateStr(60),
    created_at: dateStr(-14),
  },
  {
    id: 'cl9',
    name: 'Yoga for Beginners',
    category: 'yoga',
    description: 'Gentle yoga introduction — perfect for newcomers with no experience.',
    type: 'one_time',
    date: dateStr(1),
    start_time: '10:00',
    end_time: '11:00',
    location: 'Studio A',
    max_capacity: 15,
    booked_count: 8,
    trainer_id: 't2',
    status: 'active',
    allow_waitlist: false,
    max_waitlist: 0,
    repeat: undefined,
    end_date: null,
    created_at: dateStr(-2),
  },
  {
    id: 'cl10',
    name: 'Cardio Blast',
    category: 'cardio',
    description: 'Fast-paced cardio intervals. Treadmill, bike, and plyometrics.',
    type: 'recurring',
    date: dateStr(1),
    start_time: '17:00',
    end_time: '18:00',
    location: 'Main Floor',
    max_capacity: 20,
    booked_count: 20,  // FULL
    trainer_id: 't3',
    status: 'active',
    allow_waitlist: true,
    max_waitlist: 4,
    repeat: 'weekly',
    end_date: null,
    created_at: dateStr(-7),
  },

  // ── DAY AFTER TOMORROW ──────────────────────────────────────────────────────
  {
    id: 'cl11',
    name: 'Boxing Advanced',
    category: 'boxing',
    description: 'Advanced sparring techniques, pad work and combination drills.',
    type: 'recurring',
    date: dateStr(2),
    start_time: '06:00',
    end_time: '07:30',
    location: 'Main Floor',
    max_capacity: 10,
    booked_count: 6,
    trainer_id: 't4',
    status: 'active',
    allow_waitlist: false,
    max_waitlist: 0,
    repeat: 'weekly',
    end_date: null,
    created_at: dateStr(-4),
  },
  {
    id: 'cl12',
    name: 'General Fitness',
    category: 'general',
    description: 'Full-body functional training for all fitness levels.',
    type: 'recurring',
    date: dateStr(2),
    start_time: '17:00',
    end_time: '18:00',
    location: 'Main Floor',
    max_capacity: 20,
    booked_count: 4,
    trainer_id: 't4',
    status: 'cancelled',
    allow_waitlist: false,
    max_waitlist: 0,
    repeat: 'weekly',
    end_date: null,
    created_at: dateStr(-10),
  },

  // ── YESTERDAY (completed) ───────────────────────────────────────────────────
  {
    id: 'cl13',
    name: 'Morning HIIT',
    category: 'hiit',
    description: 'High-intensity interval training.',
    type: 'recurring',
    date: dateStr(-1),
    start_time: '06:00',
    end_time: '07:00',
    location: 'Main Floor',
    max_capacity: 25,
    booked_count: 23,
    trainer_id: 't1',
    status: 'active',
    allow_waitlist: true,
    max_waitlist: 5,
    repeat: 'weekly',
    end_date: null,
    created_at: dateStr(-14),
  },
  {
    id: 'cl14',
    name: 'Pilates Core',
    category: 'pilates',
    description: 'Core-focused Pilates.',
    type: 'recurring',
    date: dateStr(-1),
    start_time: '18:30',
    end_time: '19:30',
    location: 'Studio A',
    max_capacity: 12,
    booked_count: 11,
    trainer_id: 't2',
    status: 'active',
    allow_waitlist: false,
    max_waitlist: 0,
    repeat: 'weekly',
    end_date: null,
    created_at: dateStr(-8),
  },
];

// ── Attendees ────────────────────────────────────────────────────────────────

export const MOCK_ATTENDEES: Record<string, ClassAttendee[]> = {
  cl1: [
    { id: 'a1a', class_id: 'cl1', member_id: 'm1', member_name: 'Peter Njoroge', member_plan: 'Monthly Premium', is_walkin: false, attendance_status: 'present' },
    { id: 'a1b', class_id: 'cl1', member_id: 'm3', member_name: 'John Mutua', member_plan: 'Monthly Basic', is_walkin: false, attendance_status: 'present' },
    { id: 'a1c', class_id: 'cl1', member_id: 'm5', member_name: 'Mike Ochieng', member_plan: 'Annual Premium', is_walkin: false, attendance_status: 'present' },
    { id: 'a1d', class_id: 'cl1', member_id: 'm8', member_name: 'Wanjiku Mwangi', member_plan: 'Monthly Premium', is_walkin: false, attendance_status: 'pending' },
    { id: 'a1e', class_id: 'cl1', member_id: null, member_name: 'Kelvin Otieno (walk-in)', member_plan: undefined, is_walkin: true, attendance_status: 'present' },
  ],
  cl2: [
    { id: 'a2a', class_id: 'cl2', member_id: 'm2', member_name: 'Grace Wanjiru', member_plan: 'Annual Basic', is_walkin: false, attendance_status: 'present' },
    { id: 'a2b', class_id: 'cl2', member_id: 'm4', member_name: 'Sarah Kimani', member_plan: 'Monthly Premium', is_walkin: false, attendance_status: 'absent' },
    { id: 'a2c', class_id: 'cl2', member_id: 'm8', member_name: 'Wanjiku Mwangi', member_plan: 'Monthly Premium', is_walkin: false, attendance_status: 'pending' },
  ],
  cl5: [
    { id: 'a5a', class_id: 'cl5', member_id: 'm1', member_name: 'Peter Njoroge', member_plan: 'Monthly Premium', is_walkin: false, attendance_status: 'pending' },
    { id: 'a5b', class_id: 'cl5', member_id: 'm5', member_name: 'Mike Ochieng', member_plan: 'Annual Premium', is_walkin: false, attendance_status: 'pending' },
    { id: 'a5c', class_id: 'cl5', member_id: 'm7', member_name: 'Daniel Karanja', member_plan: 'Monthly Basic', is_walkin: false, attendance_status: 'pending' },
  ],
};

// ── Waitlist ──────────────────────────────────────────────────────────────────

export const MOCK_WAITLIST: Record<string, WaitlistEntry[]> = {
  cl3: [
    { id: 'w3a', class_id: 'cl3', member_id: 'm2', member_name: 'Grace Wanjiru', position: 1, added_at: new Date(Date.now() - 3600000).toISOString() },
    { id: 'w3b', class_id: 'cl3', member_id: 'm9', member_name: 'Tom Omondi', position: 2, added_at: new Date(Date.now() - 1800000).toISOString() },
  ],
  cl10: [
    { id: 'w10a', class_id: 'cl10', member_id: 'm6', member_name: 'Aisha Abdi', position: 1, added_at: new Date(Date.now() - 7200000).toISOString() },
    { id: 'w10b', class_id: 'cl10', member_id: 'm7', member_name: 'Daniel Karanja', position: 2, added_at: new Date(Date.now() - 5400000).toISOString() },
    { id: 'w10c', class_id: 'cl10', member_id: 'm9', member_name: 'Tom Omondi', position: 3, added_at: new Date(Date.now() - 3600000).toISOString() },
  ],
};
